os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/kingcos/Swift-CI/master/ci)"
  - eval "$(curl -sL https://raw.githubusercontent.com/kingcos/Swift-CI/master/codecov)"
